
package dbclient.view;


import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JTextField;

/**
 *
 * @author Price
 */
public class CreateSqlFile extends JDialog {

    /** Creates new form CreateSqlFile */
    public CreateSqlFile() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        createFile = new javax.swing.JButton();
        cancelCreate = new javax.swing.JButton();
        fileName = new javax.swing.JTextField();
        fileLocation = new javax.swing.JTextField();
        browseFs = new javax.swing.JButton();
        lcnLbl = new javax.swing.JLabel();
        fnLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Создать файл");
        setMinimumSize(new java.awt.Dimension(420, 150));
        setModal(true);
        setResizable(false);

        createFile.setText("OK");
        createFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createFileActionPerformed(evt);
            }
        });

        cancelCreate.setText("Отмена");
        cancelCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelCreateActionPerformed(evt);
            }
        });

        fileName.setText("Untitled.sql");
        fileName.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                fileNameInputMethodTextChanged(evt);
            }
        });

        fileLocation.setEditable(false);
        fileLocation.setText(System.getProperty("java.io.tmpdir"));

        browseFs.setText("Обзор");
        browseFs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseFsActionPerformed(evt);
            }
        });

        lcnLbl.setText("Расположение");

        fnLbl.setText("Имя файла");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(createFile, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelCreate))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lcnLbl)
                            .addComponent(fnLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fileLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                .addGap(12, 12, 12)
                                .addComponent(browseFs, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fileName))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnLbl)
                    .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browseFs)
                    .addComponent(fileLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcnLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelCreate)
                    .addComponent(createFile))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }//GEN-END:initComponents

    private void createFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createFileActionPerformed
        status = true;
        this.dispose();
    }//GEN-LAST:event_createFileActionPerformed

    private void browseFsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseFsActionPerformed
        chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = chooser.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION) {
            String directoryPath = chooser.getSelectedFile().getPath();
            fileLocation.setText(directoryPath + System.getProperty("file.separator"));
        }
    }//GEN-LAST:event_browseFsActionPerformed

    private void cancelCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelCreateActionPerformed
        status = false;
        this.dispose();
    }//GEN-LAST:event_cancelCreateActionPerformed

    private void fileNameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_fileNameInputMethodTextChanged

    }//GEN-LAST:event_fileNameInputMethodTextChanged

    public JTextField getFileLocation() {
        return fileLocation;
    }

    public JTextField getFileName() {
        return fileName;
    }

    public boolean isStatus() {
        return status;
    }
    private JFileChooser chooser;
    private boolean status = false;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseFs;
    private javax.swing.JButton cancelCreate;
    private javax.swing.JButton createFile;
    private javax.swing.JTextField fileLocation;
    private javax.swing.JTextField fileName;
    private javax.swing.JLabel fnLbl;
    private javax.swing.JLabel lcnLbl;
    // End of variables declaration//GEN-END:variables

}
