
package oraclient.view;


import javax.swing.JDialog;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Price
 */
public class ConnectionDialog extends JDialog {

    /** Creates new form FileDialog */
    public ConnectionDialog() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        connect = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        usrname = new javax.swing.JTextField();
        usernameLbl = new javax.swing.JLabel();
        pwdLbl = new javax.swing.JLabel();
        pwd = new javax.swing.JPasswordField();
        urlLbl = new javax.swing.JLabel();
        url = new javax.swing.JTextField();
        connectionNameLbl = new javax.swing.JLabel();
        connectionName = new javax.swing.JTextField();

        setModal(true);
        setResizable(false);

        connect.setText("Соединение");
        connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectActionPerformed(evt);
            }
        });

        cancel.setText("Отмена");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        usernameLbl.setText("Имя пользователя");

        pwdLbl.setText("Пароль");

        urlLbl.setText("URL соединения");

        connectionNameLbl.setText("Название соединения");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(connect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pwdLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(urlLbl, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(usernameLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(connectionNameLbl)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usrname, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(pwd)
                            .addComponent(url)
                            .addComponent(connectionName))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connectionNameLbl)
                    .addComponent(connectionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usrname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdLbl)
                    .addComponent(pwd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlLbl)
                    .addComponent(url))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connect)
                    .addComponent(cancel))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }//GEN-END:initComponents

    private void connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectActionPerformed
        status = true;
        setVisible(false);
    }//GEN-LAST:event_connectActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        status = false;
        setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    public JPasswordField getPwd() {
        return pwd;
    }

    public JTextField getUrl() {
        return url;
    }

    public JTextField getUsrname() {
        return usrname;
    }

    public JTextField getConnectionName() {
        return connectionName;
    }
    
    public boolean isStatus() { 
            return status; 
    } 
    
    private boolean status = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton connect;
    private javax.swing.JTextField connectionName;
    private javax.swing.JLabel connectionNameLbl;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JLabel pwdLbl;
    private javax.swing.JTextField url;
    private javax.swing.JLabel urlLbl;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JTextField usrname;
    // End of variables declaration//GEN-END:variables

}
