
package oraclient.view;

import java.sql.Connection;

import java.sql.DatabaseMetaData;
import java.sql.SQLException;

import java.util.Map;

import javax.swing.JButton;

import javax.swing.table.DefaultTableModel;

import oraclient.sql.conns.DBConnection;

/**
 *
 * @author Price
 */
public class SessionJDialog extends javax.swing.JDialog {

    /** Creates new form SessionJDialog */
    public SessionJDialog(java.awt.Frame parent, boolean modal, DBConnection conn) {
        super(parent, modal);
        initComponents();
        if (conn != null) {
            Map<Integer, Connection> conns = conn.getConnections();
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("База данных");
            model.addColumn("Пользователь");
            for (Map.Entry<Integer, Connection> entry : conns.entrySet()) {
                try {
                    DatabaseMetaData meta = entry.getValue().getMetaData();
                    String dbName = meta.getDatabaseProductName();
                    String userName = meta.getUserName();
                    model.addRow(new Object[] {dbName, userName});
                } catch (SQLException e) {
                }
            }
            sessionTable.setModel(model);
        }
    }

    public JButton getTerminateButton() {
        return terminateBtn;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        sessionScrollPane = new javax.swing.JScrollPane();
        sessionTable = new javax.swing.JTable();
        terminateBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Сессии");
        setModal(true);
        setResizable(false);

        sessionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        sessionScrollPane.setViewportView(sessionTable);

        terminateBtn.setText("Завершить все сессии");
        terminateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sessionScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 241, Short.MAX_VALUE)
                        .addComponent(terminateBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sessionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(terminateBtn)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }//GEN-END:initComponents

    private void terminateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terminateBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane sessionScrollPane;
    private javax.swing.JTable sessionTable;
    private javax.swing.JButton terminateBtn;
    // End of variables declaration//GEN-END:variables

}
