
package oraclient.view;

import java.sql.Connection;

import java.sql.DatabaseMetaData;
import java.sql.SQLException;

import java.util.HashMap;
import java.util.Map;

import javax.swing.JButton;

import javax.swing.table.DefaultTableModel;

import oraclient.sql.conns.DBConnection;

/**
 *
 * @author Price
 */
public class SessionJDialog extends javax.swing.JDialog {

    /** Creates new form SessionJDialog */
    public SessionJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Map<Connection, String> conns = DBConnection.getConnections();
        if (conns != null) {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("База данных");
            model.addColumn("Пользователь");
            for (Map.Entry<Connection, String> entry : conns.entrySet()) {
                try {
                    DatabaseMetaData meta = entry.getKey().getMetaData();
                    String dbName = meta.getDatabaseProductName();
                    String userName = meta.getUserName();
                    model.addRow(new Object[] {dbName, userName});
                } catch (SQLException e) {
                }
            }
            sessionTable.setModel(model);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        sessionScrollPane = new javax.swing.JScrollPane();
        sessionTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Сессии");
        setModal(true);
        setResizable(false);

        sessionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        sessionScrollPane.setViewportView(sessionTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sessionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sessionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane sessionScrollPane;
    private javax.swing.JTable sessionTable;
    // End of variables declaration//GEN-END:variables

}
